language: node_js
cache: yarn
node_js:
  - node
  - "10"
os:
  - linux
  - osx
branches:
  only:
    - master
    - "/^greenkeeper/.*$/"
script:
  - npm test
after_success:
  - yarn coverage
jobs:
  include:
    - stage: release
      if: branch IN (master, next)
      node_js: node
      script:
        - npx semantic-release
      env:
